### ISSUE TITLE
engine on_stroked failed

### ISSUE THREAD

**Issue by gfixler** [Kenny2github/plover-clr-trans-state#1]
Hi. I'm getting an error when I try to stroke this definition.

I have this mapping:

`KHR-R` -> `{plover:clear_trans_state}`

When I try to use it, I get this error popup:

```
Plover
ERROR: engine on_stroked failed
KeyError: 'clear_trans_state'
```

**Comment by Kenny2github** [comment]
Do you have the plugin installed?
![plover-clr-trans-state correctly installed](https://user-images.githubusercontent.com/28599280/158476578-d70b479a-70e0-4c64-9299-182c7d167c09.png)

**Comment by gfixler** [comment]
Yes, I have it installed.

**Comment by Kenny2github** [comment]
Odd. Unfortunately this is a case of Works On My Machine and I also don't really know what questions to ask to be able to diagnose this.

**Comment by gfixler** [comment]
Understood. I'll close this out, and let you know if I figure it out at some point.

**Comment by gfixler** [comment]
Just an update to say I tried again today, and now it works!
 `¯\_(ツ)_/¯`

**Comment by jirafey** [comment]
same issue

solved with:
change in Plover->-machine->q
change q to #
change q to S-

it should fix it but it will show itself with symbols written in qwerty "-", you would need to bind all the other unbinded keys to something so the popup wont appear with"=" or whatever else
